[package]
name = "apxm-cli"
version.workspace = true
edition.workspace = true

[dependencies]
# workspace
apxm-compiler = { version = "0.0.1", path = "../apxm-compiler" }
apxm-core = { version = "0.0.1", path = "../apxm-core" }

# Error handling
anyhow = "1.0.100"
thiserror = "2.0.17"

# CLI
clap = { version = "4.5.53", features = ["derive", "env", "wrap_help"] }

# Utilities
colored = "3.0.0"
chrono = "0.4.42"

# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

# Async runtime
tokio = { version = "1.48.0", features = ["full"] }

# Logging
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
